# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create app on Apple Developer and App Store Connect sites"
  lane :create_app do
​    produce
  end
  
  desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end
  
  desc "Upload to App Store"
  lane :release do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "DashX Demo.xcodeproj"
    )
    gym(scheme: "DashX Demo",
	configuration:"Release",
        export_options: {
                method: "app-store",
                provisioningProfiles: {"com.dashxdemo.app"=>"DashX AppStore"}
    })
  upload_to_testflight(skip_waiting_for_build_processing: true, skip_submission: true)
  end
  
  desc "Upload to AppCenter"
  lane :upload_to_appcenter do
    appcenter_upload(
      api_token: ENV["TEST_APPCENTER_API_TOKEN"],
      owner_type: "organization",
      owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
      app_name: "DashX-Demo-iOS",
      file: "./fastlane/builds/DashX Demo.ipa",
      destinations: ENV["TEST_APPCENTER_DISTRIBUTE_GROUP"],
      destination_type: "group",
      release_notes: ENV["TEST_APPCENTER_DISTRIBUTE_RELEASE_NOTES"]
    )
  end
end
