# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

WORKSPACE = "DashX Demo.xcworkspace"
XCODEPROJ = "DashX Demo.xcodeproj"
STAGING_SCHEME = "DashX Demo Staging"
PRODUCTION_SCHEME = "DashX Demo Production"
INTERNAL_TESTERS_GROUP = "Internal Testers"
DEMO_TESTERS_GROUP = "Demo Testers"

platform :ios do
  desc "Upload Release build to TestFlight for staging"
  lane :staging_release do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(xcodeproj: XCODEPROJ)
    build_app(workspace: WORKSPACE, scheme: STAGING_SCHEME)
    upload_to_testflight(
      groups: [
        INTERNAL_TESTERS_GROUP
      ],
      distribute_external: false,
      submit_beta_review: false
    )
  end

  desc "Upload Release build to TestFlight for production"
  lane :production_release do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(xcodeproj: XCODEPROJ)
    build_app(workspace: WORKSPACE, scheme: PRODUCTION_SCHEME)
    upload_to_testflight(
      groups: [
        INTERNAL_TESTERS_GROUP,
        DEMO_TESTERS_GROUP
      ],
      distribute_external: true,
      submit_beta_review: true
    )
  end

  desc "Add new devices to provisioning profile"
  lane :provision_devices do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(type: "development", force_for_new_devices: true)
  end
end
